language: node_js
node_js:
  - "8.9.4"
script:
  - npm run bot-update
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: master
  on:
    branch:
      - master
